name: auction-identity

services:
  identity-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    depends_on:
      identity-postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - identity-go-mod:/go/pkg/mod
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - identity-internal
      - rabbitmq-shared

  identity:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      identity-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - identity-internal
      - rabbitmq-shared

  identity-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity
    volumes:
      - identity-postgres-data:/var/lib/postgresql
      - ./infra/postgres/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - identity-internal

volumes:
  identity-postgres-data:
  identity-go-mod:

networks:
  identity-internal:
  rabbitmq-shared:
    external: true
    name: auction-rabbitmq-network
