port: 8080
postgres_username: "postgres"
postgres_password: "postgres"
postgres_database: "identity"
postgres_sslmode: "disable"
postgres_host: "host.docker.internal"
postgres_port: 5432
jwt_secret: "change-me"
